steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'test' ]
    timeout: 120s
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy -v $_VERSION' ]
    timeout: 1600s
substitutions:
    _VERSION: 1-0-34a